# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import car_data_service_pb2 as car__data__service__pb2


class CarDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFrames = channel.unary_stream(
                '/car_data.CarDataService/ListFrames',
                request_serializer=car__data__service__pb2.ListFramesRequest.SerializeToString,
                response_deserializer=car__data__service__pb2.SingleFrame.FromString,
                )


class CarDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.ListFrames,
                    request_deserializer=car__data__service__pb2.ListFramesRequest.FromString,
                    response_serializer=car__data__service__pb2.SingleFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'car_data.CarDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CarDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/car_data.CarDataService/ListFrames',
            car__data__service__pb2.ListFramesRequest.SerializeToString,
            car__data__service__pb2.SingleFrame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
