# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_data_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='car_data_service.proto',
  package='car_data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63\x61r_data_service.proto\x12\x08\x63\x61r_data\"?\n\x11ListFramesRequest\x12\x18\n\x10number_of_frames\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x65lay_ms\x18\x02 \x01(\x05\"\x1f\n\x0bSingleFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x32V\n\x0e\x43\x61rDataService\x12\x44\n\nListFrames\x12\x1b.car_data.ListFramesRequest\x1a\x15.car_data.SingleFrame\"\x00\x30\x01\x62\x06proto3'
)




_LISTFRAMESREQUEST = _descriptor.Descriptor(
  name='ListFramesRequest',
  full_name='car_data.ListFramesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_frames', full_name='car_data.ListFramesRequest.number_of_frames', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delay_ms', full_name='car_data.ListFramesRequest.delay_ms', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=99,
)


_SINGLEFRAME = _descriptor.Descriptor(
  name='SingleFrame',
  full_name='car_data.SingleFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='car_data.SingleFrame.frame_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['ListFramesRequest'] = _LISTFRAMESREQUEST
DESCRIPTOR.message_types_by_name['SingleFrame'] = _SINGLEFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListFramesRequest = _reflection.GeneratedProtocolMessageType('ListFramesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTFRAMESREQUEST,
  '__module__' : 'car_data_service_pb2'
  # @@protoc_insertion_point(class_scope:car_data.ListFramesRequest)
  })
_sym_db.RegisterMessage(ListFramesRequest)

SingleFrame = _reflection.GeneratedProtocolMessageType('SingleFrame', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEFRAME,
  '__module__' : 'car_data_service_pb2'
  # @@protoc_insertion_point(class_scope:car_data.SingleFrame)
  })
_sym_db.RegisterMessage(SingleFrame)



_CARDATASERVICE = _descriptor.ServiceDescriptor(
  name='CarDataService',
  full_name='car_data.CarDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=134,
  serialized_end=220,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListFrames',
    full_name='car_data.CarDataService.ListFrames',
    index=0,
    containing_service=None,
    input_type=_LISTFRAMESREQUEST,
    output_type=_SINGLEFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARDATASERVICE)

DESCRIPTOR.services_by_name['CarDataService'] = _CARDATASERVICE

# @@protoc_insertion_point(module_scope)
